apiVersion: apps/v1
kind: Deployment
metadata:
  name: shardmanager-deployment
  labels:
    keel.sh/trigger: poll
    keel.sh/match-tag: "true"
    keel.sh/policy: "force"
  annotations:
    keel.sh/pollSchedule: "@every 1m"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: votebot-shardmanager
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: votebot-shardmanager
    spec:
      containers:
      - name: site
        image: votebot/shardmanager:master
        imagePullPolicy: Always
        ports:
          - containerPort: 5465
        envFrom:
          - secretRef:
              name: env
